title: Jayaram's Blog
author: Jayaram18
email: jayaramsingh1999@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
Welcome to Jayaram's blog!


# social links
twitter_username: JayaramSingh15 # DO NOT include the @ character, or else the build will fail!
github_username:  Jayaram18 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
